version: '3.8'
services:
  nuxt:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: nuxt-app
    container_name: nuxt-app
    ports:
      - "3000:3000"
    command: npm run dev
    volumes:
      - ./frontend:/usr/src/nuxt-app
      - /usr/src/nuxt-app/node_modules